import csv, pymysql

con = pymysql.connect(host='localhost',
                     user='root',
                     password='root',
                     db='nfl',
                     charset='utf8mb4',
                     cursorclass=pymysql.cursors.DictCursor)
cur = con.cursor()
cur.execute('CREATE TABLE nflpbp (Game_Date DATE,GameID text,Drive text,qtr INT,down text,game_time text,TimeUnder text,TimeSecs INT,PlayTimeDiff text,SideofField text,yrdln text,yrdline100 text,ydstogo text,ydsnet text,GoalToGo text,FirstDown text,posteam text,DefensiveTeam text,description text,PlayAttempted text,Yards_Gained int,sp text,Touchdown text,ExPointResult text,TwoPointConv text,DefTwoPoint text,Safety text,Onsidekick text,PuntResult text,PlayType text,Passer text,Passer_ID text,PassAttempt text,PassOutcome text,PassLength text,AirYards text,YardsAfterCatch text,QBHit text,PassLocation text,InterceptionThrown text,Interceptor text,Rusher text,Rusher_ID text,RushAttempt text,RunLocation text,RunGap text,Receiver text,Receiver_ID text,Reception text,ReturnResult text,Returner text,BlockingPlayer text,Tackler1 text,Tackler2 text,FieldGoalResult text,FieldGoalDistance text,Fumble text,RecFumbTeam text,RecFumbPlayer text,Sack text,Challenge_Replay text,ChalReplayResult text,Accepted_Penalty text,PenalizedTeam text,PenaltyType text,PenalizedPlayer text,Penalty_Yards text,PosTeamScore text,DefTeamScore text,ScoreDiff text,AbsScoreDiff text,HomeTeam text,AwayTeam text,Timeout_Indicator text,Timeout_Team text,posteam_timeouts_pre text,HomeTimeouts_Remaining_Pre text,AwayTimeouts_Remaining_Pre text,HomeTimeouts_Remaining_Post text,AwayTimeouts_Remaining_Post text,No_Score_Prob text,Opp_Field_Goal_Prob text,Opp_Safety_Prob text,Opp_Touchdown_Prob text,Field_Goal_Prob text,Safety_Prob text,Touchdown_Prob text,ExPoint_Prob text,TwoPoint_Prob text,ExpPts text,EPA text,airEPA text,yacEPA text,Home_WP_pre text,Away_WP_pre text,Home_WP_post text,Away_WP_post text,Win_Prob text,WPA text,airWPA text,yacWPA text,Season text)')

with open('NFL_PlaybyPlay.csv', 'rb') as nfl:
	dr = csv.DictReader(nfl)
	to_db = [[i['Game_Date'], i['GameID'], i['Drive'], i['qtr'], i['down'], i['game_time'], i['TimeUnder'], int(float(i['TimeSecs'])), i['PlayTimeDiff'], i['SideofField'], i['yrdln'], i['yrdline100'], i['ydstogo'], i['ydsnet'], i['GoalToGo'], i['FirstDown'], i['posteam'], i['DefensiveTeam'], i['desc'], i['PlayAttempted'], i['Yards_Gained'], i['sp'], i['Touchdown'], i['ExPointResult'], i['TwoPointConv'], i['DefTwoPoint'], i['Safety'], i['Onsidekick'], i['PuntResult'], i['PlayType'], i['Passer'], i['Passer_ID'], i['PassAttempt'], i['PassOutcome'], i['PassLength'], i['AirYards'], i['YardsAfterCatch'], i['QBHit'], i['PassLocation'], i['InterceptionThrown'], i['Interceptor'], i['Rusher'], i['Rusher_ID'], i['RushAttempt'], i['RunLocation'], i['RunGap'], i['Receiver'], i['Receiver_ID'], i['Reception'], i['ReturnResult'], i['Returner'], i['BlockingPlayer'], i['Tackler1'], i['Tackler2'], i['FieldGoalResult'], i['FieldGoalDistance'], i['Fumble'], i['RecFumbTeam'], i['RecFumbPlayer'], i['Sack'], i['Challenge_Replay'], i['ChalReplayResult'], i['Accepted_Penalty'], i['PenalizedTeam'], i['PenaltyType'], i['PenalizedPlayer'], i['Penalty_Yards'], i['PosTeamScore'], i['DefTeamScore'], i['ScoreDiff'], i['AbsScoreDiff'], i['HomeTeam'], i['AwayTeam'], i['Timeout_Indicator'], i['Timeout_Team'], i['posteam_timeouts_pre'], i['HomeTimeouts_Remaining_Pre'], i['AwayTimeouts_Remaining_Pre'], i['HomeTimeouts_Remaining_Post'], i['AwayTimeouts_Remaining_Post'], i['No_Score_Prob'], i['Opp_Field_Goal_Prob'], i['Opp_Safety_Prob'], i['Opp_Touchdown_Prob'], i['Field_Goal_Prob'], i['Safety_Prob'], i['Touchdown_Prob'], i['ExPoint_Prob'], i['TwoPoint_Prob'], i['ExpPts'], i['EPA'], i['airEPA'], i['yacEPA'], i['Home_WP_pre'], i['Away_WP_pre'], i['Home_WP_post'], i['Away_WP_post'], i['Win_Prob'], i['WPA'], i['airWPA'], i['yacWPA'], i['Season']] for i in dr if 'NA' not in i['TimeSecs']]

cur.executemany("INSERT INTO nflpbp (Game_Date,GameID,Drive,qtr,down,game_time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,yrdln,yrdline100,ydstogo,ydsnet,GoalToGo,FirstDown,posteam,DefensiveTeam,description,PlayAttempted,Yards_Gained,sp,Touchdown,ExPointResult,TwoPointConv,DefTwoPoint,Safety,Onsidekick,PuntResult,PlayType,Passer,Passer_ID,PassAttempt,PassOutcome,PassLength,AirYards,YardsAfterCatch,QBHit,PassLocation,InterceptionThrown,Interceptor,Rusher,Rusher_ID,RushAttempt,RunLocation,RunGap,Receiver,Receiver_ID,Reception,ReturnResult,Returner,BlockingPlayer,Tackler1,Tackler2,FieldGoalResult,FieldGoalDistance,Fumble,RecFumbTeam,RecFumbPlayer,Sack,Challenge_Replay,ChalReplayResult,Accepted_Penalty,PenalizedTeam,PenaltyType,PenalizedPlayer,Penalty_Yards,PosTeamScore,DefTeamScore,ScoreDiff,AbsScoreDiff,HomeTeam,AwayTeam,Timeout_Indicator,Timeout_Team,posteam_timeouts_pre,HomeTimeouts_Remaining_Pre,AwayTimeouts_Remaining_Pre,HomeTimeouts_Remaining_Post,AwayTimeouts_Remaining_Post,No_Score_Prob,Opp_Field_Goal_Prob,Opp_Safety_Prob,Opp_Touchdown_Prob,Field_Goal_Prob,Safety_Prob,Touchdown_Prob,ExPoint_Prob,TwoPoint_Prob,ExpPts,EPA,airEPA,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)", to_db)
con.commit()
con.close()