import csv, sqlite3
import pdb


#pdb.set_trace()
con = sqlite3.connect('nfl.db')
cur = con.cursor()
cur.executescript('''DROP TABLE IF EXISTS nflpbp;
	CREATE TABLE nflpbp (Game_Date DATE,GameID text,Drive text,qtr INT,down text,game_time TEXT,TimeUnder TEXT,TimeSecs INT,PlayTimeDiff TEXT,SideofField TEXT,yrdln text,yrdline100 text,ydstogo text,ydsnet text,GoalToGo TEXT,FirstDown TEXT,posteam TEXT,DefensiveTeam TEXT,desc TEXT,PlayAttempted TEXT,Yards_Gained int,sp TEXT,Touchdown TEXT,ExPointResult TEXT,TwoPointConv TEXT,DefTwoPoint TEXT,Safety TEXT,Onsidekick TEXT,PuntResult TEXT,PlayType TEXT,Passer TEXT,Passer_ID TEXT,PassAttempt TEXT,PassOutcome TEXT,PassLength text,AirYards text,YardsAfterCatch text,QBHit TEXT,PassLocation TEXT,InterceptionThrown TEXT,Interceptor TEXT,Rusher TEXT,Rusher_ID TEXT,RushAttempt TEXT,RunLocation TEXT,RunGap TEXT,Receiver TEXT,Receiver_ID TEXT,Reception TEXT,ReturnResult TEXT,Returner TEXT,BlockingPlayer TEXT,Tackler1 TEXT,Tackler2 TEXT,FieldGoalResult TEXT,FieldGoalDistance TEXT,Fumble TEXT,RecFumbTeam TEXT,RecFumbPlayer TEXT,Sack TEXT,Challenge_Replay TEXT,ChalReplayResult TEXT,Accepted_Penalty TEXT,PenalizedTeam TEXT,PenaltyType TEXT,PenalizedPlayer TEXT,Penalty_Yards TEXT,PosTeamScore TEXT,DefTeamScore TEXT,ScoreDiff TEXT,AbsScoreDiff TEXT,HomeTeam TEXT,AwayTeam TEXT,Timeout_Indicator TEXT,Timeout_Team TEXT,posteam_timeouts_pre TEXT,HomeTimeouts_Remaining_Pre TEXT,AwayTimeouts_Remaining_Pre TEXT,HomeTimeouts_Remaining_Post TEXT,AwayTimeouts_Remaining_Post TEXT,No_Score_Prob TEXT,Opp_Field_Goal_Prob TEXT,Opp_Safety_Prob TEXT,Opp_Touchdown_Prob TEXT,Field_Goal_Prob TEXT,Safety_Prob TEXT,Touchdown_Prob TEXT,ExPoint_Prob TEXT,TwoPoint_Prob TEXT,ExpPts TEXT,EPA TEXT,airEPA TEXT,yacEPA TEXT,Home_WP_pre TEXT,Away_WP_pre TEXT,Home_WP_post TEXT,Away_WP_post TEXT,Win_Prob TEXT,WPA TEXT,airWPA TEXT,yacWPA TEXT,Season TEXT)''')

with open('NFL_PlaybyPlay.csv', 'rb') as nfl:
	dr = csv.DictReader(nfl)
	#to_db = [i.values() for i in dr]
	to_db = [[i['Game_Date'], i['GameID'], i['Drive'], i['qtr'], i['down'], i['game_time'], i['TimeUnder'], i['TimeSecs'], i['PlayTimeDiff'], i['SideofField'], i['yrdln'], i['yrdline100'], i['ydstogo'], i['ydsnet'], i['GoalToGo'], i['FirstDown'], i['posteam'], i['DefensiveTeam'], i['desc'], i['PlayAttempted'], i['Yards_Gained'], i['sp'], i['Touchdown'], i['ExPointResult'], i['TwoPointConv'], i['DefTwoPoint'], i['Safety'], i['Onsidekick'], i['PuntResult'], i['PlayType'], i['Passer'], i['Passer_ID'], i['PassAttempt'], i['PassOutcome'], i['PassLength'], i['AirYards'], i['YardsAfterCatch'], i['QBHit'], i['PassLocation'], i['InterceptionThrown'], i['Interceptor'], i['Rusher'], i['Rusher_ID'], i['RushAttempt'], i['RunLocation'], i['RunGap'], i['Receiver'], i['Receiver_ID'], i['Reception'], i['ReturnResult'], i['Returner'], i['BlockingPlayer'], i['Tackler1'], i['Tackler2'], i['FieldGoalResult'], i['FieldGoalDistance'], i['Fumble'], i['RecFumbTeam'], i['RecFumbPlayer'], i['Sack'], i['Challenge_Replay'], i['ChalReplayResult'], i['Accepted_Penalty'], i['PenalizedTeam'], i['PenaltyType'], i['PenalizedPlayer'], i['Penalty_Yards'], i['PosTeamScore'], i['DefTeamScore'], i['ScoreDiff'], i['AbsScoreDiff'], i['HomeTeam'], i['AwayTeam'], i['Timeout_Indicator'], i['Timeout_Team'], i['posteam_timeouts_pre'], i['HomeTimeouts_Remaining_Pre'], i['AwayTimeouts_Remaining_Pre'], i['HomeTimeouts_Remaining_Post'], i['AwayTimeouts_Remaining_Post'], i['No_Score_Prob'], i['Opp_Field_Goal_Prob'], i['Opp_Safety_Prob'], i['Opp_Touchdown_Prob'], i['Field_Goal_Prob'], i['Safety_Prob'], i['Touchdown_Prob'], i['ExPoint_Prob'], i['TwoPoint_Prob'], i['ExpPts'], i['EPA'], i['airEPA'], i['yacEPA'], i['Home_WP_pre'], i['Away_WP_pre'], i['Home_WP_post'], i['Away_WP_post'], i['Win_Prob'], i['WPA'], i['airWPA'], i['yacWPA'], i['Season']] for i in dr]

cur.executemany("INSERT INTO nflpbp (Game_Date,GameID,Drive,qtr,down,game_time,TimeUnder,TimeSecs,PlayTimeDiff,SideofField,yrdln,yrdline100,ydstogo,ydsnet,GoalToGo,FirstDown,posteam,DefensiveTeam,desc,PlayAttempted,Yards_Gained,sp,Touchdown,ExPointResult,TwoPointConv,DefTwoPoint,Safety,Onsidekick,PuntResult,PlayType,Passer,Passer_ID,PassAttempt,PassOutcome,PassLength,AirYards,YardsAfterCatch,QBHit,PassLocation,InterceptionThrown,Interceptor,Rusher,Rusher_ID,RushAttempt,RunLocation,RunGap,Receiver,Receiver_ID,Reception,ReturnResult,Returner,BlockingPlayer,Tackler1,Tackler2,FieldGoalResult,FieldGoalDistance,Fumble,RecFumbTeam,RecFumbPlayer,Sack,Challenge_Replay,ChalReplayResult,Accepted_Penalty,PenalizedTeam,PenaltyType,PenalizedPlayer,Penalty_Yards,PosTeamScore,DefTeamScore,ScoreDiff,AbsScoreDiff,HomeTeam,AwayTeam,Timeout_Indicator,Timeout_Team,posteam_timeouts_pre,HomeTimeouts_Remaining_Pre,AwayTimeouts_Remaining_Pre,HomeTimeouts_Remaining_Post,AwayTimeouts_Remaining_Post,No_Score_Prob,Opp_Field_Goal_Prob,Opp_Safety_Prob,Opp_Touchdown_Prob,Field_Goal_Prob,Safety_Prob,Touchdown_Prob,ExPoint_Prob,TwoPoint_Prob,ExpPts,EPA,airEPA,yacEPA,Home_WP_pre,Away_WP_pre,Home_WP_post,Away_WP_post,Win_Prob,WPA,airWPA,yacWPA,Season) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);", to_db)
con.commit()
con.close()